FROM openjdk:8-jdk

# Définir un répertoire de travail
WORKDIR /opt/talend

# Copier le JAR de JobServer dans le conteneur
COPY path/to/your/talend-jobserver.jar ./talend-jobserver.jar

# Exposer le port JobServer
EXPOSE 8040

# Commande pour démarrer JobServer
CMD ["java", "-jar", "talend-jobserver.jar"]
