services:
  postgres:
    container_name: docker_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/db/data:/var/lib/postgresql/data
      - ${PWD}/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - app-network-api

  api:
    build: ./src
    container_name: app-fastapi
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ${PWD}/src/:/usr/src/app/
    ports:
      - 8002:8000
    depends_on:
      - postgres
    networks:
      - app-network-api

volumes:
  data:

networks:
  app-network-api:
    driver: bridge